'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { Breadcrumb, Layout, Menu, Modal, Button, theme } from 'antd';
const { Header, Content, Footer } = Layout;
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const items = [
  {
    key: 1,
    label: <Link href='/'>Home</Link>,
  },
  {
    key: 2,
    label: <Link href='/institution'>Área da Instituição</Link>,
  },
  {
    key: 3,
    label: <Link href='/farmer'>Área do Fazendeiro</Link>,
  },
];

export default function RootLayout({ children }) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
        <Header
          style={{
            display: 'flex',
            alignItems: 'center',
          }}
        >
          <div className="demo-logo" />
          <Menu
            theme="dark"
            mode="horizontal"
            defaultSelectedKeys={['1']}
            items={items}
            style={{
              flex: 1,
              minWidth: 0,
            }}
          />
        </Header>
        <Content
          style={{
            padding: '25px 25px',
          }}
        >
          <div
            style={{
              background: colorBgContainer,
              minHeight: 280,
              padding: 24,
              borderRadius: borderRadiusLG,
            }}
          >
            {children}
          </div>
        </Content>
        <Footer
          style={{
            textAlign: 'center',
          }}
        >
          Insurance on Ethereum • {new Date().getFullYear()}
        </Footer>
      </Layout>
      </body>
    </html>
  );
}
